version: "3"

networks:
  factory-management:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    networks:
      - factory-management
        # ipv4_address: 172.30.0.100